apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-on-k8s-deployment
spec: 
  selector: 
    matchLabels: 
      app: spring-boot-on-k8s 
  replicas: 3 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angular 
    spec: 
      containers: 
      - name: spring-boot-on-k8s 
        image: vveerender/spring-boot-on-k8s:#{Build.BuildId}#
        ports: 
        - containerPort: 80 



