apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-on-k8s-deployment
spec: 
  selector: 
    matchLabels: 
      app: spring-boot-on-k8s 
  replicas: 3 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: spring-boot-on-k8s  
    spec: 
      containers: 
      - name: spring-boot-on-k8s 
        image: vveerender/spring-boot-on-k8s:#{Build.BuildId}#
        ports: 
        - containerPort: 8090 
---     
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-on-k8s-service
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: spring-boot-on-k8s-service
 



